# LESSON 18 Библиотека pandas
# Работа с несколькими таблицами

## Примеры урока

In [13]:
import pandas as pd

### Объединение таблиц Pandas DataFrame

In [15]:
path = 'data/'
log_1 = pd.read_csv(path+'log_1.csv', sep=';')
log_2 = pd.read_csv(path+'log_2.csv', sep=';')

In [16]:
log_1

        ID  SOURCE                 DATE
0   720251  yandex  17.10.2019 11:17:17
1   720250  google  17.10.2019 11:09:32
2   720255  yandex  17.10.2019 12:04:34
3   720257  google  17.10.2019 12:17:11
4   720258  yandex  17.10.2019 12:40:07
5   720281  yandex  17.10.2019 14:10:31
6   720290  yandex  17.10.2019 14:37:11
7   720297  yandex  17.10.2019 15:21:57
8   720301  yandex  17.10.2019 16:20:13
9   720303  yandex  17.10.2019 16:26:25
10  720253  google  17.10.2019 11:53:01
11  720256  yandex  17.10.2019 12:12:44
12  720262  yandex  17.10.2019 12:53:55

In [17]:
log_2

       ID  SOURCE                 DATE
0  720474  yandex  18.10.2019 12:28:59
1  720477  yandex  18.10.2019 12:53:05
2  720479      vk  18.10.2019 13:04:41
3  720483  google  18.10.2019 13:24:01

In [19]:
# df1 = log_1.append(log_2)
df1 = pd.concat([log_1, log_2], ignore_index=True)
df1

        ID  SOURCE                 DATE
0   720251  yandex  17.10.2019 11:17:17
1   720250  google  17.10.2019 11:09:32
2   720255  yandex  17.10.2019 12:04:34
3   720257  google  17.10.2019 12:17:11
4   720258  yandex  17.10.2019 12:40:07
5   720281  yandex  17.10.2019 14:10:31
6   720290  yandex  17.10.2019 14:37:11
7   720297  yandex  17.10.2019 15:21:57
8   720301  yandex  17.10.2019 16:20:13
9   720303  yandex  17.10.2019 16:26:25
10  720253  google  17.10.2019 11:53:01
11  720256  yandex  17.10.2019 12:12:44
12  720262  yandex  17.10.2019 12:53:55
13  720474  yandex  18.10.2019 12:28:59
14  720477  yandex  18.10.2019 12:53:05
15  720479      vk  18.10.2019 13:04:41
16  720483  google  18.10.2019 13:24:01

In [20]:
# Сохраним данные в книгу Excel
df1.to_excel(path+"output.xlsx")

In [21]:
# Чтобы указать имя листа:
df1.to_excel(path+"output.xlsx",
             sheet_name='Sheet_name_1')

In [22]:
# Если вы хотите писать более чем на один лист в книге, необходимо указать объект `ExcelWriter`:
df2 = df1.copy()
with pd.ExcelWriter(path+'output.xlsx') as writer:  
    df1.to_excel(writer, sheet_name='Sheet_name_1')
    df2.to_excel(writer, sheet_name='Sheet_name_2')

In [23]:
# `ExcelWriter` также можно использовать для добавления к существующему файлу Excel:
with pd.ExcelWriter(path+'output.xlsx', engine="openpyxl", mode='a') as writer:  
    df2.to_excel(writer, sheet_name='Sheet_name_3')

In [25]:
# log_1.append(log_2, ignore_index=True)
pd.concat([log_1, log_2], ignore_index=True)

        ID  SOURCE                 DATE
0   720251  yandex  17.10.2019 11:17:17
1   720250  google  17.10.2019 11:09:32
2   720255  yandex  17.10.2019 12:04:34
3   720257  google  17.10.2019 12:17:11
4   720258  yandex  17.10.2019 12:40:07
5   720281  yandex  17.10.2019 14:10:31
6   720290  yandex  17.10.2019 14:37:11
7   720297  yandex  17.10.2019 15:21:57
8   720301  yandex  17.10.2019 16:20:13
9   720303  yandex  17.10.2019 16:26:25
10  720253  google  17.10.2019 11:53:01
11  720256  yandex  17.10.2019 12:12:44
12  720262  yandex  17.10.2019 12:53:55
13  720474  yandex  18.10.2019 12:28:59
14  720477  yandex  18.10.2019 12:53:05
15  720479      vk  18.10.2019 13:04:41
16  720483  google  18.10.2019 13:24:01

In [26]:
# log_2.append([{'ID':1, 'SOURCE':'user', 'DATE':'now'}])
pd.concat([log_2, pd.DataFrame([{'ID':1, 'SOURCE':'user', 'DATE':'now'}])], ignore_index=True)

       ID  SOURCE                 DATE
0  720474  yandex  18.10.2019 12:28:59
1  720477  yandex  18.10.2019 12:53:05
2  720479      vk  18.10.2019 13:04:41
3  720483  google  18.10.2019 13:24:01
4       1    user                  now

In [27]:
# log_2.append([(1, 'user', 'now')])
pd.concat([log_2, pd.DataFrame([(1, 'user', 'now')], columns=log_2.columns)], ignore_index=True)

       ID  SOURCE                 DATE
0  720474  yandex  18.10.2019 12:28:59
1  720477  yandex  18.10.2019 12:53:05
2  720479      vk  18.10.2019 13:04:41
3  720483  google  18.10.2019 13:24:01
4       1    user                  now

In [28]:
pd.concat((log_1, log_2))

        ID  SOURCE                 DATE
0   720251  yandex  17.10.2019 11:17:17
1   720250  google  17.10.2019 11:09:32
2   720255  yandex  17.10.2019 12:04:34
3   720257  google  17.10.2019 12:17:11
4   720258  yandex  17.10.2019 12:40:07
5   720281  yandex  17.10.2019 14:10:31
6   720290  yandex  17.10.2019 14:37:11
7   720297  yandex  17.10.2019 15:21:57
8   720301  yandex  17.10.2019 16:20:13
9   720303  yandex  17.10.2019 16:26:25
10  720253  google  17.10.2019 11:53:01
11  720256  yandex  17.10.2019 12:12:44
12  720262  yandex  17.10.2019 12:53:55
0   720474  yandex  18.10.2019 12:28:59
1   720477  yandex  18.10.2019 12:53:05
2   720479      vk  18.10.2019 13:04:41
3   720483  google  18.10.2019 13:24:01

In [29]:
# порядок таблиц, передаваемых для объединения важен и соответствует порядку строк в результате.
pd.concat((log_2, log_1))

        ID  SOURCE                 DATE
0   720474  yandex  18.10.2019 12:28:59
1   720477  yandex  18.10.2019 12:53:05
2   720479      vk  18.10.2019 13:04:41
3   720483  google  18.10.2019 13:24:01
0   720251  yandex  17.10.2019 11:17:17
1   720250  google  17.10.2019 11:09:32
2   720255  yandex  17.10.2019 12:04:34
3   720257  google  17.10.2019 12:17:11
4   720258  yandex  17.10.2019 12:40:07
5   720281  yandex  17.10.2019 14:10:31
6   720290  yandex  17.10.2019 14:37:11
7   720297  yandex  17.10.2019 15:21:57
8   720301  yandex  17.10.2019 16:20:13
9   720303  yandex  17.10.2019 16:26:25
10  720253  google  17.10.2019 11:53:01
11  720256  yandex  17.10.2019 12:12:44
12  720262  yandex  17.10.2019 12:53:55

In [30]:
# Так же заметим, что нумерация так же сохраняется от исходных таблиц. 
# Избавиться от неё так же можно с помощью `ignore_index=True`.
pd.concat((log_1, log_2), ignore_index=True)

        ID  SOURCE                 DATE
0   720251  yandex  17.10.2019 11:17:17
1   720250  google  17.10.2019 11:09:32
2   720255  yandex  17.10.2019 12:04:34
3   720257  google  17.10.2019 12:17:11
4   720258  yandex  17.10.2019 12:40:07
5   720281  yandex  17.10.2019 14:10:31
6   720290  yandex  17.10.2019 14:37:11
7   720297  yandex  17.10.2019 15:21:57
8   720301  yandex  17.10.2019 16:20:13
9   720303  yandex  17.10.2019 16:26:25
10  720253  google  17.10.2019 11:53:01
11  720256  yandex  17.10.2019 12:12:44
12  720262  yandex  17.10.2019 12:53:55
13  720474  yandex  18.10.2019 12:28:59
14  720477  yandex  18.10.2019 12:53:05
15  720479      vk  18.10.2019 13:04:41
16  720483  google  18.10.2019 13:24:01

In [32]:
# объединить таблицы не построчно, а по столбцам.
log_2_success = pd.read_csv(path+'log_2_success.csv', sep=';')
log_2_success

       ID  SUCCESS
0  720474     True
1  720477    False
2  720479    False
3  720483     True

In [33]:
pd.concat((log_2, log_2_success))

       ID  SOURCE                 DATE SUCCESS
0  720474  yandex  18.10.2019 12:28:59     NaN
1  720477  yandex  18.10.2019 12:53:05     NaN
2  720479      vk  18.10.2019 13:04:41     NaN
3  720483  google  18.10.2019 13:24:01     NaN
0  720474     NaN                  NaN    True
1  720477     NaN                  NaN   False
2  720479     NaN                  NaN   False
3  720483     NaN                  NaN    True

In [34]:
# Чтобы объединить таблицы по столбцам изменим ось (направление) объединения 
# со строк (0) на столбцы (1) с помощью атрибута `axis`:
pd.concat((log_2, log_2_success), axis = 1)

       ID  SOURCE                 DATE      ID  SUCCESS
0  720474  yandex  18.10.2019 12:28:59  720474     True
1  720477  yandex  18.10.2019 12:53:05  720477    False
2  720479      vk  18.10.2019 13:04:41  720479    False
3  720483  google  18.10.2019 13:24:01  720483     True

In [35]:
# Т.к. столбец ID дублируется, давайте его удалим, просто сделав выборку нужных данных 
# (напоминаем, объединять можно как фреймы так pandas.Series):
pd.concat((log_2, log_2_success['SUCCESS']), axis = 1)

       ID  SOURCE                 DATE  SUCCESS
0  720474  yandex  18.10.2019 12:28:59     True
1  720477  yandex  18.10.2019 12:53:05    False
2  720479      vk  18.10.2019 13:04:41    False
3  720483  google  18.10.2019 13:24:01     True

In [36]:
# Следующий пример показывает некорректное объединение данных.
log_2_success_unsorted = pd.read_csv(path+'log_2_success_unsorted.csv', sep=';')
log_2_success_unsorted

       ID  SUCCESS
0  720477    False
1  720479    False
2  720474     True
3  720483     True

In [37]:
pd.concat((log_2, log_2_success_unsorted), axis = 1)

       ID  SOURCE                 DATE      ID  SUCCESS
0  720474  yandex  18.10.2019 12:28:59  720477    False
1  720477  yandex  18.10.2019 12:53:05  720479    False
2  720479      vk  18.10.2019 13:04:41  720474     True
3  720483  google  18.10.2019 13:24:01  720483     True

In [38]:
# Чтобы избежать этого, используем функцию `merge`
pd.merge(log_2, log_2_success_unsorted, on=('ID'))

       ID  SOURCE                 DATE  SUCCESS
0  720474  yandex  18.10.2019 12:28:59     True
1  720477  yandex  18.10.2019 12:53:05    False
2  720479      vk  18.10.2019 13:04:41    False
3  720483  google  18.10.2019 13:24:01     True

In [40]:
# объединим 3 таблицы:
# pd.merge(log_1.append(log_2), log_2_success_unsorted, on=('ID'))
pd.merge(pd.concat([log_1, log_2], ignore_index=True), log_2_success_unsorted, on='ID')

       ID  SOURCE                 DATE  SUCCESS
0  720474  yandex  18.10.2019 12:28:59     True
1  720477  yandex  18.10.2019 12:53:05    False
2  720479      vk  18.10.2019 13:04:41    False
3  720483  google  18.10.2019 13:24:01     True

In [42]:
# все строки, которым не нашлось парных записей для merge просто удалены
# оставить их, то можно использовать `how ='left'`:
# pd.merge(log_1.append(log_2), log_2_success_unsorted, on=('ID'), how ='left')
pd.merge(pd.concat([log_1, log_2], ignore_index=True), log_2_success_unsorted, on='ID', how='left')

        ID  SOURCE                 DATE SUCCESS
0   720251  yandex  17.10.2019 11:17:17     NaN
1   720250  google  17.10.2019 11:09:32     NaN
2   720255  yandex  17.10.2019 12:04:34     NaN
3   720257  google  17.10.2019 12:17:11     NaN
4   720258  yandex  17.10.2019 12:40:07     NaN
5   720281  yandex  17.10.2019 14:10:31     NaN
6   720290  yandex  17.10.2019 14:37:11     NaN
7   720297  yandex  17.10.2019 15:21:57     NaN
8   720301  yandex  17.10.2019 16:20:13     NaN
9   720303  yandex  17.10.2019 16:26:25     NaN
10  720253  google  17.10.2019 11:53:01     NaN
11  720256  yandex  17.10.2019 12:12:44     NaN
12  720262  yandex  17.10.2019 12:53:55     NaN
13  720474  yandex  18.10.2019 12:28:59    True
14  720477  yandex  18.10.2019 12:53:05   False
15  720479      vk  18.10.2019 13:04:41   False
16  720483  google  18.10.2019 13:24:01    True

In [44]:
# объединить таблицы, находя соответствие не по колонкам, а по индексам
log_1_i = pd.read_csv(path+'log_1.csv', sep=';', index_col='ID')
log_2_i = pd.read_csv(path+'log_2.csv', sep=';', index_col='ID')
log_2_success_unsorted_i = pd.read_csv(path+'log_2_success_unsorted.csv', sep=';', index_col='ID')
log_2_i.head()

        SOURCE                 DATE
ID
720474  yandex  18.10.2019 12:28:59
720477  yandex  18.10.2019 12:53:05
720479      vk  18.10.2019 13:04:41
720483  google  18.10.2019 13:24:01

In [45]:
log_2_success_unsorted_i.head()

        SUCCESS
ID
720477    False
720479    False
720474     True
720483     True

In [49]:
# pd.merge(log_1_i.append(log_2_i), log_2_success_unsorted_i, on=('ID'), how ='left')
pd.merge(pd.concat([log_1_i, log_2_i], ignore_index=True), log_2_success_unsorted_i, left_index=True, right_index=True, how='left')

    SOURCE                 DATE SUCCESS
0   yandex  17.10.2019 11:17:17     NaN
1   google  17.10.2019 11:09:32     NaN
2   yandex  17.10.2019 12:04:34     NaN
3   google  17.10.2019 12:17:11     NaN
4   yandex  17.10.2019 12:40:07     NaN
5   yandex  17.10.2019 14:10:31     NaN
6   yandex  17.10.2019 14:37:11     NaN
7   yandex  17.10.2019 15:21:57     NaN
8   yandex  17.10.2019 16:20:13     NaN
9   yandex  17.10.2019 16:26:25     NaN
10  google  17.10.2019 11:53:01     NaN
11  yandex  17.10.2019 12:12:44     NaN
12  yandex  17.10.2019 12:53:55     NaN
13  yandex  18.10.2019 12:28:59     NaN
14  yandex  18.10.2019 12:53:05     NaN
15      vk  18.10.2019 13:04:41     NaN
16  google  18.10.2019 13:24:01     NaN

In [50]:
log_2_success_unsorted_i.index.names = ['NEW_ID']
log_2_success_unsorted_i

        SUCCESS
NEW_ID
720477    False
720479    False
720474     True
720483     True

In [51]:
# pd.merge(log_1_i.append(log_2_i), log_2_success_unsorted_i, how ='left', left_index=True, right_index=True)
pd.merge(pd.concat([log_1_i, log_2_i], ignore_index=True), log_2_success_unsorted_i, how='left', left_index=True, right_index=True)

    SOURCE                 DATE SUCCESS
0   yandex  17.10.2019 11:17:17     NaN
1   google  17.10.2019 11:09:32     NaN
2   yandex  17.10.2019 12:04:34     NaN
3   google  17.10.2019 12:17:11     NaN
4   yandex  17.10.2019 12:40:07     NaN
5   yandex  17.10.2019 14:10:31     NaN
6   yandex  17.10.2019 14:37:11     NaN
7   yandex  17.10.2019 15:21:57     NaN
8   yandex  17.10.2019 16:20:13     NaN
9   yandex  17.10.2019 16:26:25     NaN
10  google  17.10.2019 11:53:01     NaN
11  yandex  17.10.2019 12:12:44     NaN
12  yandex  17.10.2019 12:53:55     NaN
13  yandex  18.10.2019 12:28:59     NaN
14  yandex  18.10.2019 12:53:05     NaN
15      vk  18.10.2019 13:04:41     NaN
16  google  18.10.2019 13:24:01     NaN

In [52]:
# pd.merge(log_1_i.append(log_2_i), log_2_success_unsorted_i, how ='right', left_index=True, right_index=True)
pd.merge(pd.concat([log_1_i, log_2_i], ignore_index=True), log_2_success_unsorted_i, how='right', left_index=True, right_index=True)

       SOURCE DATE  SUCCESS
NEW_ID
720477    NaN  NaN    False
720479    NaN  NaN    False
720474    NaN  NaN     True
720483    NaN  NaN     True

In [55]:
# Предположим, что у одной таблицы мы хотим использовать индекс, а у другой колонку для объединения. 
# Тогда помимо указанных выше аргументов нам потребуется 1 (или оба) аргумента:    
# * left_on - имя колонки из левой таблицы (1-й аргумент) для объединения
# * right_on - имя колонки из правой таблицы (2-й аргумент) для объединения
# pd.merge(log_1_i.append(log_2_i), log_2_success_unsorted_i, how ='left', left_on=('ID'), right_index=True)
pd.merge(pd.concat([log_1_i, log_2_i], ignore_index=True), log_2_success_unsorted_i, how='left', left_index=True, right_index=True)

    SOURCE                 DATE SUCCESS
0   yandex  17.10.2019 11:17:17     NaN
1   google  17.10.2019 11:09:32     NaN
2   yandex  17.10.2019 12:04:34     NaN
3   google  17.10.2019 12:17:11     NaN
4   yandex  17.10.2019 12:40:07     NaN
5   yandex  17.10.2019 14:10:31     NaN
6   yandex  17.10.2019 14:37:11     NaN
7   yandex  17.10.2019 15:21:57     NaN
8   yandex  17.10.2019 16:20:13     NaN
9   yandex  17.10.2019 16:26:25     NaN
10  google  17.10.2019 11:53:01     NaN
11  yandex  17.10.2019 12:12:44     NaN
12  yandex  17.10.2019 12:53:55     NaN
13  yandex  18.10.2019 12:28:59     NaN
14  yandex  18.10.2019 12:53:05     NaN
15      vk  18.10.2019 13:04:41     NaN
16  google  18.10.2019 13:24:01     NaN

### Связь один ко многим

In [56]:
orders = pd.read_csv(path+'orders.csv', sep=';')
products = pd.read_csv(path+'products.csv', sep=';')

In [57]:
orders

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1

In [58]:
products

    Product_ID                                   Name  Price CURRENCY
0           47                   Шатны Полосатый рейс   2999      RUR
1           51               Платье Аленький цветочек   4999      RUR
2           53                 Штаны Цветочная Поляна   4999      RUR
3           71                    Платье Ночная Жизнь   7999      RUR
4           74               Платье Ночная Жизнь XXXL   8999      RUR
5           86                     Носки Простые, муж     45      RUR
6           91                     Носки Честные, муж     50      RUR
7          103                  Носки Подарочные, муж    199      RUR
8          104                  Носки Подарочные, жен    249      RUR
9          124                   Носки беговые Camino    999      RUR
10         137              Гольфы детские Снегурочка     99      RUR
11         138               Гольфы детские Питер Пен     99      RUR
12         139                       Сумка для носков    500      RUR
13         140  Товар, которому не придумано название      1      RUR

In [59]:
d =pd.merge(orders, products, how ='left', left_on=('ID товара'), right_on=('Product_ID'))
d

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,86.0,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,104.0,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,104.0,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,104.0,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,124.0,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,91.0,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,103.0,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,104.0,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,74.0,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,53.0,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,137.0,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,47.0,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,71.0,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,86.0,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,51.0,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN

In [60]:
pd.merge(orders, products, how='inner', left_on=('ID товара'), right_on=('Product_ID'))

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103,"Носки Подарочные, муж",199,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,86,"Носки Простые, муж",45,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,104,"Носки Подарочные, жен",249,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,104,"Носки Подарочные, жен",249,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,104,"Носки Подарочные, жен",249,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103,"Носки Подарочные, муж",199,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,124,Носки беговые Camino,999,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,91,"Носки Честные, муж",50,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,103,"Носки Подарочные, муж",199,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,104,"Носки Подарочные, жен",249,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,74,Платье Ночная Жизнь XXXL,8999,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,53,Штаны Цветочная Поляна,4999,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,137,Гольфы детские Снегурочка,99,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,47,Шатны Полосатый рейс,2999,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,71,Платье Ночная Жизнь,7999,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,86,"Носки Простые, муж",45,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,51,Платье Аленький цветочек,4999,RUR

### Сортировка

In [61]:
orders.sort_values('ID товара')

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1

In [62]:
# сортировать на основе нескольких колонок
orders.sort_values(by=['ID товара', 'ID Покупателя'], ascending=[False, True])

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1

### reset_index()

In [63]:
# нужно переиндексировать строки
orders.sort_values(by=['ID товара'], ascending=False).reset_index()

,index,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1
1,12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1
2,6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
3,3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3
5,2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
6,4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
7,0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
8,8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
9,5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
10,7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
11,1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
12,15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1
13,10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1
14,14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1
15,11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1
16,16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1
17,13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1

In [64]:
# новый DataFrame также хранит старые индексы. Если они не нужны, их можно удалить
orders.sort_values(by = ['ID товара'], ascending = False).reset_index(drop = True)

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1
1,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1
2,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3
5,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
6,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
7,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
9,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
10,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
11,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
12,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1
15,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1
17,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1

## Этап 3: Работа с несколькими таблицами

In [2]:
# Подготовка данных
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Настройка отображения
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_rows', 20)

print("="*70)
print("ЭТАП 3: РАБОТА С НЕСКОЛЬКИМИ ТАБЛИЦАМИ")
print("="*70)

# Создадим несколько связанных таблиц для демонстрации
np.random.seed(42)

# Таблица 1: Клиенты
customers = pd.DataFrame({
    'customer_id': range(1, 11),
    'name': [f'Клиент_{i}' for i in range(1, 11)],
    'city': np.random.choice(['Москва', 'СПб', 'Казань', 'Новосибирск', 'Екатеринбург'], 10),
    'age': np.random.randint(25, 60, 10),
    'total_purchases': np.random.randint(1, 20, 10)
})

# Таблица 2: Заказы
orders = pd.DataFrame({
    'order_id': range(101, 121),
    'customer_id': np.random.choice(range(1, 11), 20),
    'order_date': pd.date_range('2024-01-01', periods=20, freq='D'),
    'amount': np.random.uniform(100, 5000, 20).round(2),
    'status': np.random.choice(['completed', 'pending', 'cancelled'], 20, p=[0.7, 0.2, 0.1])
})

# Таблица 3: Товары
products = pd.DataFrame({
    'product_id': range(1, 9),
    'product_name': ['Ноутбук', 'Телефон', 'Планшет', 'Наушники', 'Мышь', 'Клавиатура', 'Монитор', 'Принтер'],
    'category': ['Электроника', 'Электроника', 'Электроника', 'Аксессуары', 'Аксессуары', 'Аксессуары', 'Электроника', 'Офис'],
    'price': np.random.uniform(500, 50000, 8).round(0)
})

# Таблица 4: Детали заказов (связь многие ко многим)
order_details = pd.DataFrame({
    'order_id': np.random.choice(range(101, 121), 35),
    'product_id': np.random.choice(range(1, 9), 35),
    'quantity': np.random.randint(1, 5, 35),
    'discount': np.random.uniform(0, 0.3, 35).round(2)
})

# Таблица 5: Бонусы клиентов (дополнительная таблица)
customer_bonus = pd.DataFrame({
    'customer_id': range(1, 11),
    'bonus_points': np.random.randint(0, 5000, 10),
    'status': np.random.choice(['gold', 'silver', 'bronze'], 10, p=[0.2, 0.3, 0.5])
})

# Таблица 6: Новые клиенты (для демонстрации append/concat)
new_customers = pd.DataFrame({
    'customer_id': range(11, 16),
    'name': [f'Новый_клиент_{i}' for i in range(11, 16)],
    'city': ['Москва', 'СПб', 'Казань', 'Новосибирск', 'Сочи'],
    'age': np.random.randint(20, 55, 5),
    'total_purchases': [0, 0, 0, 0, 0]
})

# Таблица 7: Заказы 2023 года (для демонстрации concat)
orders_2023 = pd.DataFrame({
    'order_id': range(1, 11),
    'customer_id': np.random.choice(range(1, 11), 10),
    'order_date': pd.date_range('2023-01-01', periods=10, freq='ME'),
    'amount': np.random.uniform(100, 4500, 10).round(2),
    'status': np.random.choice(['completed', 'pending', 'cancelled'], 10, p=[0.7, 0.2, 0.1])
})

print("\nИсходные таблицы созданы:")
print(f"Клиенты: {customers.shape}")
print(f"Заказы: {orders.shape}")
print(f"Товары: {products.shape}")
print(f"Детали заказов: {order_details.shape}")
print(f"Бонусы клиентов: {customer_bonus.shape}")
print(f"Новые клиенты: {new_customers.shape}")
print(f"Заказы 2023: {orders_2023.shape}")

======================================================================
ЭТАП 3: РАБОТА С НЕСКОЛЬКИМИ ТАБЛИЦАМИ
======================================================================

Исходные таблицы созданы:
Клиенты: (10, 5)
Заказы: (20, 5)
Товары: (8, 4)
Детали заказов: (35, 4)
Бонусы клиентов: (10, 3)
Новые клиенты: (5, 5)
Заказы 2023: (10, 5)

### 1. МЕТОД APPEND()

In [5]:
print("\n" + "="*70)
print("1. МЕТОД APPEND()")
print("="*70)

# ========== 1. Метод append() ==========
print("\n--- 1.1 Базовое использование append() ---")
print("\n✅ ВАЖНО: append() удален в pandas 2.0+, используйте pd.concat()")

# ========== 1. Добавление строк (вместо append) ==========
print("\n--- 1.1 Добавление одной строки с помощью pd.concat() ---")

# Вместо df.append() используем pd.concat()
new_row = pd.DataFrame({
    'customer_id': [16],
    'name': ['Иванов Иван'],
    'city': ['Москва'],
    'age': [35],
    'total_purchases': [0]
})

# Добавляем одну строку
customers_appended = pd.concat([customers, new_row], ignore_index=True)
print("Добавление одной строки:")
print(f"Исходный размер: {len(customers)}")
print(f"Размер после добавления: {len(customers_appended)}")
print("Последние 3 строки:")
print(customers_appended.tail(3))

# Добавление нескольких строк
new_rows = pd.DataFrame({
    'customer_id': [17, 18],
    'name': ['Петров Петр', 'Сидорова Анна'],
    'city': ['СПб', 'Казань'],
    'age': [28, 42],
    'total_purchases': [0, 0]
})

customers_appended = pd.concat([customers, new_rows], ignore_index=True)
print(f"\nДобавление нескольких строк: {len(customers_appended)} строк")

# ========== 1.2 Добавление строк с разными столбцами ==========
print("\n--- 1.2 Добавление строк с разными столбцами ---")

incomplete_row = pd.DataFrame({
    'customer_id': [19],
    'name': ['Неполный'],
    'city': ['Москва']
    # Нет age и total_purchases
})

customers_with_nan = pd.concat([customers, incomplete_row], ignore_index=True)
print("Добавление строки с недостающими столбцами:")
print(customers_with_nan.tail(2))
print("NaN заполняются автоматически")

======================================================================
1. МЕТОД APPEND()
======================================================================

--- 1.1 Базовое использование append() ---

✅ ВАЖНО: append() удален в pandas 2.0+, используйте pd.concat()

--- 1.1 Добавление одной строки с помощью pd.concat() ---
Добавление одной строки:
Исходный размер: 10
Размер после добавления: 11
Последние 3 строки:
    customer_id         name          city  age  total_purchases
8             9     Клиент_9        Казань   57                3
9            10    Клиент_10  Екатеринбург   36                5
10           16  Иванов Иван        Москва   35                0

Добавление нескольких строк: 12 строк

--- 1.2 Добавление строк с разными столбцами ---
Добавление строки с недостающими столбцами:
    customer_id       name          city   age  total_purchases
9            10  Клиент_10  Екатеринбург  36.0              5.0
10           19   Неполный        Москва   NaN              NaN
NaN заполняются автоматически

### 2 Функция pd.concat()

In [6]:
# ========== 2. Функция pd.concat() ==========
print("\n--- 2.1 Вертикальное объединение (axis=0) ---")

# Объединение по строкам
all_customers = pd.concat([customers, new_customers], ignore_index=True)
print("Объединение клиентов + новые клиенты:")
print(f"Размер: {all_customers.shape}")
print(all_customers.tail(5))

# Объединение нескольких таблиц с метками
all_orders = pd.concat([orders_2023, orders], ignore_index=True, keys=['2023', '2024'])
print("\nОбъединение заказов 2023 и 2024:")
print(f"Размер: {all_orders.shape}")
print("Первые 3 и последние 3 строки:")
print(pd.concat([all_orders.head(3), all_orders.tail(3)]))

# ========== 2.2 Горизонтальное объединение (axis=1) ==========
print("\n--- 2.2 Горизонтальное объединение (axis=1) ---")

# Создаем таблицы с общим индексом
customer_basic = customers[['customer_id', 'name', 'city']].copy()
customer_stats = customers[['customer_id', 'total_purchases']].copy()

# Устанавливаем индексы для горизонтального объединения
customer_basic.set_index('customer_id', inplace=True)
customer_stats.set_index('customer_id', inplace=True)

# Горизонтальное объединение
customer_full = pd.concat([customer_basic, customer_stats], axis=1)
print("Горизонтальное объединение с индексами:")
print(customer_full.head())

# ========== 2.3 Разные типы соединения при concat ==========
print("\n--- 2.3 Типы соединения при concat ---")

# Создаем таблицы с разными индексами
df1 = pd.DataFrame({'A': [1, 2, 3]}, index=[0, 1, 2])
df2 = pd.DataFrame({'B': [4, 5, 6]}, index=[2, 3, 4])

print("Таблица 1:")
print(df1)
print("\nТаблица 2:")
print(df2)

print("\nInner join (только пересекающиеся индексы):")
print(pd.concat([df1, df2], axis=1, join='inner'))

print("\nOuter join (все индексы):")
print(pd.concat([df1, df2], axis=1, join='outer'))

--- 2.1 Вертикальное объединение (axis=0) ---
Объединение клиентов + новые клиенты:
Размер: (15, 5)
    customer_id             name         city  age  total_purchases
10           11  Новый_клиент_11       Москва   52                0
11           12  Новый_клиент_12          СПб   23                0
12           13  Новый_клиент_13       Казань   52                0
13           14  Новый_клиент_14  Новосибирск   33                0
14           15  Новый_клиент_15         Сочи   40                0

Объединение заказов 2023 и 2024:
Размер: (30, 5)
Первые 3 и последние 3 строки:
    order_id  customer_id order_date   amount     status
0          1            4 2023-01-31  1202.03  completed
1          2            8 2023-02-28  2695.43  completed
2          3            8 2023-03-31  4407.13  completed
27       118            3 2024-01-18  2744.49  completed
28       119            1 2024-01-19  2975.08  completed
29       120            4 2024-01-20  4829.75  completed

--- 2.2 Горизонтальное объединение (axis=1) ---
Горизонтальное объединение с индексами:
                 name          city  total_purchases
customer_id
1            Клиент_1   Новосибирск               12
2            Клиент_2  Екатеринбург               17
3            Клиент_3        Казань               10
4            Клиент_4  Екатеринбург               16
5            Клиент_5  Екатеринбург               15

--- 2.3 Типы соединения при concat ---
Таблица 1:
   A
0  1
1  2
2  3

Таблица 2:
   B
2  4
3  5
4  6

Inner join (только пересекающиеся индексы):
   A  B
2  3  4

Outer join (все индексы):
     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  4.0
3  NaN  5.0
4  NaN  6.0

### 3. Функции pd.merge() и df.join()

In [7]:
# ========== 3. Функции pd.merge() и df.join() ==========
print("\n--- 3.1 pd.merge() - основные типы соединений ---")

# Восстанавливаем индексы для демонстрации
customers_reset = customers.copy()
orders_reset = orders.copy()

# Inner join (по умолчанию)
inner_join = pd.merge(customers_reset, orders_reset, on='customer_id', how='inner')
print("INNER JOIN (только совпадающие записи):")
print(f"Клиентов: {len(customers_reset)}, Заказов: {len(orders_reset)}")
print(f"Результат inner join: {len(inner_join)} строк")
print(inner_join.head())

# Left join
left_join = pd.merge(customers_reset, orders_reset, on='customer_id', how='left')
print("\nLEFT JOIN (все клиенты + их заказы):")
print(f"Результат left join: {len(left_join)} строк")
print("Клиенты без заказов:")
print(left_join[left_join['order_id'].isna()][['customer_id', 'name']].drop_duplicates())

# Right join
right_join = pd.merge(customers_reset, orders_reset, on='customer_id', how='right')
print("\nRIGHT JOIN (все заказы + информация о клиентах):")
print(f"Результат right join: {len(right_join)} строк")

# Outer join
outer_join = pd.merge(customers_reset, orders_reset, on='customer_id', how='outer')
print("\nOUTER JOIN (все клиенты и все заказы):")
print(f"Результат outer join: {len(outer_join)} строк")

# ========== 3.2 Merge с разными именами столбцов ==========
print("\n--- 3.2 Merge с разными именами столбцов ---")

# Переименовываем столбец для демонстрации
customers_renamed = customers_reset.rename(columns={'customer_id': 'cust_id'})
print("Merge с разными именами столбцов:")
merged_diff = pd.merge(customers_renamed, orders_reset, left_on='cust_id', right_on='customer_id', how='inner')
print(merged_diff[['cust_id', 'name', 'order_id', 'amount']].head())

# ========== 3.3 Merge по нескольким столбцам ==========
print("\n--- 3.3 Merge по нескольким столбцам ---")

# Создаем дополнительную таблицу с составным ключом
customer_segments = pd.DataFrame({
    'city': ['Москва', 'СПб', 'Казань', 'Новосибирск', 'Екатеринбург'],
    'age_group': ['25-35', '36-50', '25-35', '36-50', '51+'],
    'segment': ['Premium', 'Standard', 'Premium', 'Standard', 'Basic']
})

# Добавляем age_group в customers
customers_with_group = customers_reset.copy()
customers_with_group['age_group'] = pd.cut(customers_with_group['age'], 
                                            bins=[0, 35, 50, 100], 
                                            labels=['25-35', '36-50', '51+'])

print("Merge по двум столбцам (city и age_group):")
merged_multi = pd.merge(customers_with_group, customer_segments, on=['city', 'age_group'], how='left')
print(merged_multi[['name', 'city', 'age', 'age_group', 'segment']].head())

# ========== 3.4 Метод .join() ==========
print("\n--- 3.4 Метод .join() ---")

# .join() используется для объединения по индексу
customers_indexed = customers_reset.set_index('customer_id')
bonus_indexed = customer_bonus.set_index('customer_id')

print("Использование .join():")
customers_with_bonus = customers_indexed.join(bonus_indexed, how='left', lsuffix='_cust', rsuffix='_bonus')
print(customers_with_bonus[['name', 'bonus_points', 'status']].head())

--- 3.1 pd.merge() - основные типы соединений ---
INNER JOIN (только совпадающие записи):
Клиентов: 10, Заказов: 20
Результат inner join: 20 строк
   customer_id      name          city  age  total_purchases  order_id  \
0            1  Клиент_1   Новосибирск   48               12       119
1            2  Клиент_2  Екатеринбург   27               17       106
2            2  Клиент_2  Екатеринбург   27               17       109
3            2  Клиент_2  Екатеринбург   27               17       114
4            3  Клиент_3        Казань   46               10       101

  order_date   amount     status
0 2024-01-19  2975.08  completed
1 2024-01-06   253.44  completed
2 2024-01-09  2036.24  completed
3 2024-01-14  2652.09  cancelled
4 2024-01-01   992.96  completed

LEFT JOIN (все клиенты + их заказы):
Результат left join: 21 строк
Клиенты без заказов:
    customer_id      name
11            6  Клиент_6

RIGHT JOIN (все заказы + информация о клиентах):
Результат right join: 20 строк

OUTER JOIN (все клиенты и все заказы):
Результат outer join: 21 строк

--- 3.2 Merge с разными именами столбцов ---
Merge с разными именами столбцов:
   cust_id      name  order_id   amount
0        1  Клиент_1       119  2975.08
1        2  Клиент_2       106   253.44
2        2  Клиент_2       109  2036.24
3        2  Клиент_2       114  2652.09
4        3  Клиент_3       101   992.96

--- 3.3 Merge по нескольким столбцам ---
Merge по двум столбцам (city и age_group):
       name          city  age age_group   segment
0  Клиент_1   Новосибирск   48     36-50  Standard
1  Клиент_2  Екатеринбург   27     25-35       NaN
2  Клиент_3        Казань   46     36-50       NaN
3  Клиент_4  Екатеринбург   26     25-35       NaN
4  Клиент_5  Екатеринбург   48     36-50       NaN

--- 3.4 Метод .join() ---
Использование .join():
                 name  bonus_points  status
customer_id
1            Клиент_1          1154  bronze
2            Клиент_2          4499    gold
3            Клиент_3          3191    gold
4            Клиент_4          1696  bronze
5            Клиент_5          3991    gold

### 4. Связь один ко многим

In [8]:
# ========== 4. Связь один ко многим ==========
print("\n--- 4.1 Пример один ко многим ---")

# Один клиент -> много заказов
customer_orders = pd.merge(customers_reset, orders_reset, on='customer_id', how='inner')
print("Связь 'один клиент - много заказов':")
customer_order_counts = customer_orders.groupby('customer_id').size()
for cust_id in [1, 5, 9]:
    print(f"Клиент {cust_id}: {customer_order_counts.get(cust_id, 0)} заказов")

# Демонстрация с детальным выводом
print("\nДетали заказов клиента 1:")
customer_1_orders = customer_orders[customer_orders['customer_id'] == 1]
print(customer_1_orders[['order_id', 'order_date', 'amount', 'status']])

# ========== 4.2 Агрегация данных при связи один ко многим ==========
print("\n--- 4.2 Агрегация при связи один ко многим ---")

# Агрегируем заказы для каждого клиента
customer_stats = customer_orders.groupby('customer_id').agg({
    'order_id': 'count',
    'amount': ['sum', 'mean', 'max']
}).round(2)

customer_stats.columns = ['total_orders', 'total_amount', 'avg_amount', 'max_amount']
print("Агрегированная статистика по клиентам:")
print(customer_stats)

# Добавляем агрегированные данные обратно к клиентам
customers_with_stats = pd.merge(customers_reset, customer_stats, on='customer_id', how='left')
customers_with_stats.fillna(0, inplace=True)
print("\nКлиенты с агрегированной статистикой:")
print(customers_with_stats[['name', 'total_orders', 'total_amount', 'avg_amount']])

--- 4.1 Пример один ко многим ---
Связь 'один клиент - много заказов':
Клиент 1: 1 заказов
Клиент 5: 2 заказов
Клиент 9: 3 заказов

Детали заказов клиента 1:
   order_id order_date   amount     status
0       119 2024-01-19  2975.08  completed

--- 4.2 Агрегация при связи один ко многим ---
Агрегированная статистика по клиентам:
             total_orders  total_amount  avg_amount  max_amount
customer_id
1                       1       2975.08     2975.08     2975.08
2                       3       4941.77     1647.26     2652.09
3                       2       3737.45     1868.72     2744.49
4                       3      13866.69     4622.23     4829.75
5                       2       5078.44     2539.22     2895.18
7                       3      10921.22     3640.41     4238.22
8                       1       3761.87     3761.87     3761.87
9                       3       7086.34     2362.11     3663.63
10                      2       6340.68     3170.34     4640.63

Клиенты с агрегированной статистикой:
        name  total_orders  total_amount  avg_amount
0   Клиент_1           1.0       2975.08     2975.08
1   Клиент_2           3.0       4941.77     1647.26
2   Клиент_3           2.0       3737.45     1868.72
3   Клиент_4           3.0      13866.69     4622.23
4   Клиент_5           2.0       5078.44     2539.22
5   Клиент_6           0.0          0.00        0.00
6   Клиент_7           3.0      10921.22     3640.41
7   Клиент_8           1.0       3761.87     3761.87
8   Клиент_9           3.0       7086.34     2362.11
9  Клиент_10           2.0       6340.68     3170.34

### 5. Сортировка

In [9]:
# ========== 5. Сортировка ==========
print("\n--- 5.1 Сортировка по одному столбцу ---")

# По возрастанию
sorted_by_age = customers_reset.sort_values('age')
print("Сортировка по возрасту (по возрастанию):")
print(sorted_by_age[['name', 'age', 'city']].head())

# По убыванию
sorted_by_purchases = customers_reset.sort_values('total_purchases', ascending=False)
print("\nСортировка по покупкам (по убыванию):")
print(sorted_by_purchases[['name', 'total_purchases', 'city']].head())

# ========== 5.2 Сортировка по нескольким столбцам ==========
print("\n--- 5.2 Сортировка по нескольким столбцам ---")

# Сортировка по городу и возрасту
sorted_multi = customers_reset.sort_values(['city', 'age'], ascending=[True, False])
print("Сортировка по городу (А-Я) и возрасту (по убыванию):")
print(sorted_multi[['name', 'city', 'age']])

--- 5.1 Сортировка по одному столбцу ---
Сортировка по возрасту (по возрастанию):
        name  age          city
3   Клиент_4   26  Екатеринбург
6   Клиент_7   26        Казань
1   Клиент_2   27  Екатеринбург
9  Клиент_10   36  Екатеринбург
7   Клиент_8   45        Казань

Сортировка по покупкам (по убыванию):
       name  total_purchases          city
6  Клиент_7               19        Казань
1  Клиент_2               17  Екатеринбург
3  Клиент_4               16  Екатеринбург
5  Клиент_6               15           СПб
4  Клиент_5               15  Екатеринбург

--- 5.2 Сортировка по нескольким столбцам ---
Сортировка по городу (А-Я) и возрасту (по убыванию):
        name          city  age
4   Клиент_5  Екатеринбург   48
9  Клиент_10  Екатеринбург   36
1   Клиент_2  Екатеринбург   27
3   Клиент_4  Екатеринбург   26
8   Клиент_9        Казань   57
2   Клиент_3        Казань   46
7   Клиент_8        Казань   45
6   Клиент_7        Казань   26
0   Клиент_1   Новосибирск   48
5   Клиент_6           СПб   54

### 6. reset_index()

In [10]:
# ========== 6. reset_index() ==========
print("\n--- 6.1 Базовое использование reset_index() ---")

# Создаем DataFrame с нестандартным индексом
customers_indexed = customers_reset.set_index('customer_id')
print("DataFrame с индексом customer_id:")
print(customers_indexed.head())

# Сброс индекса
customers_reset_index = customers_indexed.reset_index()
print("\nПосле reset_index():")
print(customers_reset_index.head())

# ========== 6.2 Сброс индекса с удалением старого ==========
print("\n--- 6.2 Сброс индекса с удалением старого ---")

customers_drop_index = customers_indexed.reset_index(drop=True)
print("Сброс индекса с drop=True (старый индекс удален):")
print(customers_drop_index.head())
print(f"Индекс: {customers_drop_index.index}")

# ========== 6.3 reset_index() после группировки ==========
print("\n--- 6.3 reset_index() после группировки ---")

# Группировка создает мультииндекс
grouped = customers_reset.groupby('city')['age'].mean().round(1)
print("Результат группировки (city как индекс):")
print(grouped)

print("\nПосле reset_index():")
grouped_reset = grouped.reset_index()
print(grouped_reset)

--- 6.1 Базовое использование reset_index() ---
DataFrame с индексом customer_id:
                 name          city  age  total_purchases
customer_id
1            Клиент_1   Новосибирск   48               12
2            Клиент_2  Екатеринбург   27               17
3            Клиент_3        Казань   46               10
4            Клиент_4  Екатеринбург   26               16
5            Клиент_5  Екатеринбург   48               15

После reset_index():
   customer_id      name          city  age  total_purchases
0            1  Клиент_1   Новосибирск   48               12
1            2  Клиент_2  Екатеринбург   27               17
2            3  Клиент_3        Казань   46               10
3            4  Клиент_4  Екатеринбург   26               16
4            5  Клиент_5  Екатеринбург   48               15

--- 6.2 Сброс индекса с удалением старого ---
Сброс индекса с drop=True (старый индекс удален):
       name          city  age  total_purchases
0  Клиент_1   Новосибирск   48               12
1  Клиент_2  Екатеринбург   27               17
2  Клиент_3        Казань   46               10
3  Клиент_4  Екатеринбург   26               16
4  Клиент_5  Екатеринбург   48               15
Индекс: RangeIndex(start=0, stop=10, step=1)

--- 6.3 reset_index() после группировки ---
Результат группировки (city как индекс):
city
Екатеринбург    34.2
Казань          43.5
Новосибирск     48.0
СПб             54.0
Name: age, dtype: float64

После reset_index():
           city   age
0  Екатеринбург  34.2
1        Казань  43.5
2   Новосибирск  48.0
3           СПб  54.0

## 7. Примеры с реальными данными

In [12]:
# ========== 7. Примеры с реальными данными ==========
print("\n--- 7.1 Кейс: Анализ продаж ---")

# Объединяем все таблицы для полного анализа
full_sales_data = (order_details
                   .merge(orders[['order_id', 'customer_id', 'order_date', 'status']], on='order_id')
                   .merge(customers_reset[['customer_id', 'name', 'city', 'age']], on='customer_id')
                   .merge(products, on='product_id'))

print("Полные данные о продажах:")
print(f"Размер: {full_sales_data.shape}")
print("\nПервые 5 строк:")
print(full_sales_data[['order_id', 'name', 'city', 'product_name', 'quantity', 'discount']].head())

# Добавляем вычисляемые столбцы
full_sales_data['total'] = full_sales_data['quantity'] * full_sales_data['price'] * (1 - full_sales_data['discount'])
full_sales_data['total'] = full_sales_data['total'].round(2)

# Анализ по городам
city_analysis = full_sales_data.groupby('city').agg({
    'total': ['sum', 'mean', 'count']
}).round(2)
city_analysis.columns = ['total_revenue', 'avg_order_value', 'num_orders']
print("\nАнализ продаж по городам:")
print(city_analysis.sort_values('total_revenue', ascending=False))

print("\n" + "="*70)
print("ИТОГОВЫЙ ЧЕК-ЛИСТ ПО ЭТАПУ 3 (pandas 2.0+)")
print("="*70)

checklist = {
    "Добавление строк": "✅ (pd.concat() вместо append)",
    "pd.concat()": "✅ (вертикальное и горизонтальное)",
    "pd.merge()": "✅ (inner, left, right, outer)",
    "df.join()": "✅ (объединение по индексу)",
    "Связь один ко многим": "✅",
    "Сортировка": "✅ (по одному/нескольким столбцам)",
    "reset_index()": "✅ (базовый и с мультииндексом)",
    "Реальные кейсы": "✅ (анализ продаж)"
}

for key, value in checklist.items():
    print(f"{key}: {value}")

print("\n" + "="*70)
print("ЭТАП 3 УСПЕШНО ЗАВЕРШЕН!")
print("="*70)

# Бонус: Краткий справочник
print("\n📚 КРАТКИЙ СПРАВОЧНИК ПО РАБОТЕ С ТАБЛИЦАМИ (pandas 2.0+):")
print("""
1. pd.concat([df1, df2])                    # Вертикальное объединение
2. pd.concat([df1, df2], axis=1)            # Горизонтальное объединение
3. pd.merge(df1, df2, on='key')             # Объединение по ключу
4. df1.join(df2)                            # Объединение по индексу
5. df.sort_values('col')                    # Сортировка по столбцу
6. df.reset_index()                         # Сброс индекса
7. pd.concat([df, new_row])                 # Добавление строки (ВМЕСТО append)
""")

--- 7.1 Кейс: Анализ продаж ---
Полные данные о продажах:
Размер: (35, 13)

Первые 5 строк:
   order_id      name          city product_name  quantity  discount
0       105  Клиент_7        Казань      Ноутбук         4      0.19
1       114  Клиент_2  Екатеринбург      Планшет         1      0.16
2       107  Клиент_4  Екатеринбург      Монитор         3      0.03
3       109  Клиент_2  Екатеринбург   Клавиатура         1      0.25
4       115  Клиент_4  Екатеринбург      Принтер         2      0.10

Анализ продаж по городам:
              total_revenue  avg_order_value  num_orders
city
Екатеринбург     1429691.97         62160.52          23
Казань            908418.84         90841.88          10
Новосибирск       109609.84         54804.92           2

======================================================================
ИТОГОВЫЙ ЧЕК-ЛИСТ ПО ЭТАПУ 3 (pandas 2.0+)
======================================================================
Добавление строк: ✅ (pd.concat() вместо append)
pd.concat(): ✅ (вертикальное и горизонтальное)
pd.merge(): ✅ (inner, left, right, outer)
df.join(): ✅ (объединение по индексу)
Связь один ко многим: ✅
Сортировка: ✅ (по одному/нескольким столбцам)
reset_index(): ✅ (базовый и с мультииндексом)
Реальные кейсы: ✅ (анализ продаж)

======================================================================
ЭТАП 3 УСПЕШНО ЗАВЕРШЕН!
======================================================================

📚 КРАТКИЙ СПРАВОЧНИК ПО РАБОТЕ С ТАБЛИЦАМИ (pandas 2.0+):

1. pd.concat([df1, df2])                    # Вертикальное объединение
2. pd.concat([df1, df2], axis=1)            # Горизонтальное объединение
3. pd.merge(df1, df2, on='key')             # Объединение по ключу
4. df1.join(df2)                            # Объединение по индексу
5. df.sort_values('col')                    # Сортировка по столбцу
6. df.reset_index()                         # Сброс индекса
7. pd.concat([df, new_row])                 # Добавление строки (ВМЕСТО append)