# LESSON 16
# Библиотека pandas

In [34]:
import pandas as pd
import numpy as np

## Примеры урока

In [35]:
# создадим Series объект
import pandas as pd
s = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
print(s)
print('=='*30)

x = pd.Series(np.random.randint(-5, 6, 10),
              index=list('abcdefghij'))
print(x)
print('=='*30)

print('вывод индексов')
print(s.index)
print(x.index)

a    1
b    2
c    3
d    4
dtype: int64
============================================================
a    3
b   -4
c   -3
d    3
e   -5
f   -1
g   -5
h   -3
i    2
j   -3
dtype: int32
============================================================
вывод индексов
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [8]:
# Важно отметить, что элементы индекса могут иметь одинаковые значения:
y = pd.Series(np.random.randint(-5, 6, 10),
              index=['a']*5 + ['b']*5)
y

a    3
a   -5
a    2
a   -2
a    2
b   -5
b   -1
b    2
b   -5
b    5
dtype: int32

In [10]:
# Для создания `Series` необязательно указывать индексы, 
# `pandas` автоматически проставит числовой индекс. 
# Также `Series` можно создавать, передавая не только список с данными, 
# но и словарь, ключи которого станут индексами в созданном `Series`.
d = {'Moscow': 1000, 'London': 300, 'Prague': None}
cities = pd.Series(d)
print(cities)

# Если вместе со словарем указан еще и индекс, то из данных будут извлечены 
# только те элементы, ключи которых присутствуют в `index`:
data = {i: np.random.randint(10) for i in 'abcdefghij'}
z = pd.Series(data)
z = pd.Series(data, index=list('facdxyz'))
print(z)

Moscow    1000.0
London     300.0
Prague       NaN
dtype: float64
f    7.0
a    4.0
c    4.0
d    1.0
x    NaN
y    NaN
z    NaN
dtype: float64

In [11]:
# Для ключей, которых нет в `data`, но есть в `index` 
# создаются значения `NaN`, которые обозначают отсутствующие элементы.
w = pd.Series(777, index=list('abcdefghij'))
w

a    777
b    777
c    777
d    777
e    777
f    777
g    777
h    777
i    777
j    777
dtype: int64

In [14]:
q = pd.Series(np.random.randint(-5, 6, 10),
              index=list('abcdefghij'))
print(q)
print('=='*30)
print('=='*30)

print('Извлечение разреженного среза (среза с заданным шагом 2):')
print(q[::2])
print('=='*30)

a    3
b    4
c   -1
d   -3
e    1
f   -5
g    0
h   -4
i   -4
j    5
dtype: int32
============================================================
============================================================
Извлечение разреженного среза (среза с заданным шагом 2):
a    3
c   -1
e    1
g    0
i   -4
dtype: int32
============================================================

In [21]:
# Вернуть значение в `Series` можно по индексу
print(cities['Moscow'])
print(cities[['Moscow', 'London']])
print('=='*30)

# Можно проверить наличие метки в `Series`
print('London' in cities)
print(cities.keys(), cities.values)

1000.0
Moscow    1000.0
London     300.0
dtype: float64
============================================================
True
Index(['Moscow', 'London', 'Prague'], dtype='object') [1000.  300.   nan]

In [22]:
# выбрать некоторые строки, которые удовлетворяют некоторым условиям
print(cities < 1000)
print('=='*30)
print(cities[cities < 1000])

Moscow    False
London     True
Prague    False
dtype: bool
============================================================
London    300.0
dtype: float64

In [24]:
# можем поменять значение в `Series`
cities['Moscow'] = 100
cities

Moscow    100.0
London    300.0
Prague      NaN
dtype: float64

In [25]:
cities[cities < 1000] = 3
cities

Moscow    3.0
London    3.0
Prague    NaN
dtype: float64

In [26]:
cities*5

Moscow    15.0
London    15.0
Prague     NaN
dtype: float64

In [27]:
cities[cities.isnull()]

Prague   NaN
dtype: float64

In [28]:
s1 = pd.Series(np.arange(5),
               index=list('abcde'))
s2 = pd.Series(np.arange(5, 10),
               index=list('acexy'))
s1, s2

(a    0
 b    1
 c    2
 d    3
 e    4
 dtype: int64,
 a    5
 c    6
 e    7
 x    8
 y    9
 dtype: int64)

In [29]:
s1 + s2

a     5.0
b     NaN
c     8.0
d     NaN
e    11.0
x     NaN
y     NaN
dtype: float64

In [30]:
import pandas as pd
import numpy as np

In [32]:
# данные о файле:  https://www.kaggle.com/hesh97/titanicdataset-traincsv
titanic = pd.read_csv('titanic.csv', index_col=0)
titanic.shape

(891, 11)

In [33]:
titanic.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [34]:
titanic.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [35]:
print(titanic.shape)
print('=='*30)

print(titanic.columns)
print('=='*30)

print(titanic.dtypes)
print('=='*30)

(891, 11)
============================================================
Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')
============================================================
Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object
============================================================

In [36]:
titanic[['Survived', 'Pclass']].head()

             Survived  Pclass
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3

In [37]:
# Прочитать из файла CSV 10 первых строк
titanic = pd.read_csv('titanic.csv', nrows=10)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [38]:
# Прочитать из файла CSV 10 первых строк и колоки 'Name', 'Sex', 'Survived'
titanic = pd.read_csv('titanic.csv', nrows=10, usecols=['Name', 'Sex', 'Survived'])
titanic

   Survived                                               Name     Sex
0         0                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         1                             Heikkinen, Miss. Laina  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4         0                           Allen, Mr. William Henry    male
5         0                                   Moran, Mr. James    male
6         0                            McCarthy, Mr. Timothy J    male
7         0                     Palsson, Master. Gosta Leonard    male
8         1  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9         1                Nasser, Mrs. Nicholas (Adele Achem)  female

In [39]:
# Более полную информацию о датасете мы можем получить с помощью `info()`
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  10 non-null     int64
 1   Name      10 non-null     object
 2   Sex       10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [42]:
# Прочитать из файла CSV 10 первых строк
titanic = pd.read_csv('titanic.csv', nrows=10)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [43]:
#изменить тип данных при необходимости
titanic.loc[:,'Fare'] = titanic.loc[:,'Fare'].astype('int64')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.0,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.0,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.0,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.0,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.0,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.0,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.0,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0,NaN,C

In [51]:
titanic = pd.read_csv('titanic.csv', index_col=0)

In [52]:
print(titanic.iloc[-1])

Survived                      0
Pclass                        3
Name        Dooley, Mr. Patrick
Sex                        male
Age                        32.0
SibSp                         0
Parch                         0
Ticket                   370376
Fare                       7.75
Cabin                       NaN
Embarked                      Q
Name: 891, dtype: object

In [55]:
print(titanic.iloc[-1, 4])
print(titanic.loc[1, 'Name'])

32.0
Braund, Mr. Owen Harris

In [56]:
titanic.iloc[0:6,0:4]

,Survived,Pclass,Name,Sex
PassengerId,,,,
1,0,3,"Braund, Mr. Owen Harris",male
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
3,1,3,"Heikkinen, Miss. Laina",female
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
5,0,3,"Allen, Mr. William Henry",male
6,0,3,"Moran, Mr. James",male

In [57]:
titanic.loc[0:6, 'Survived':'Age']

,Survived,Pclass,Name,Sex,Age
PassengerId,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
3,1,3,"Heikkinen, Miss. Laina",female,26.0
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
5,0,3,"Allen, Mr. William Henry",male,35.0
6,0,3,"Moran, Mr. James",male,NaN

In [58]:
titanic[titanic['Age'] > 60] # люди старше 60

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [59]:
#Отобрать DataFrame по нескольким условиям полей "Age" и "Sex" (пол - мужской, возраст - больше 60)
titanic[(titanic['Sex'] == 'male') & (titanic['Age'] > 60)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [60]:
# Отобрать DataFrame по условию столбца "Age" (где отсутсвуют значения)
titanic[titanic['Age'].isnull()]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [61]:
# Отобрать DataFrame по полю "Age" (между 30 и 40)
titanic = pd.read_csv('titanic.csv', nrows=25)
titanic[titanic['Age'].between(30, 40)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S

In [62]:
# Отобрать каждую 20-ую строку и столбцы ['Age', 'Name', 'Survived']
titanic = pd.read_csv('titanic.csv', nrows=100)
titanic.iloc[::20, :][['Age', 'Name', 'Survived']]

     Age                                            Name  Survived
0   22.0                         Braund, Mr. Owen Harris         0
20  35.0                            Fynney, Mr. Joseph J         0
40  40.0  Ahlin, Mrs. Johan (Johanna Persdotter Larsson)         0
60  22.0                           Sirayanian, Mr. Orsen         0
80  22.0                            Waelens, Mr. Achille         0

In [63]:
# Заменить в столбце Embarked "S" на число "3"
titanic = pd.read_csv('titanic.csv', nrows=5)
titanic['Embarked'].replace('S', 3).to_frame()

  Embarked
0        3
1        C
2        3
3        3
4        3

In [64]:
#Посмотреть информацию объекта DataFrame (по первым 10 строкам)
titanic = pd.read_csv('titanic.csv', nrows=10)
# Формат каждого столбца
print('\n', 'Формат столбцов:')
print(titanic.dtypes)
# Размерность DataFrame
print('\n', 'Размерность:')
print(titanic.shape)
# Общая статистика
print('\n', 'Общая статистика')
print(titanic.describe())

 Формат столбцов:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

 Размерность:
(10, 12)

 Общая статистика
       PassengerId   Survived     Pclass        Age      SibSp      Parch  \
count     10.00000  10.000000  10.000000   9.000000  10.000000  10.000000
mean       5.50000   0.500000   2.300000  28.111111   0.700000   0.300000
std        3.02765   0.527046   0.948683  14.945271   0.948683   0.674949
min        1.00000   0.000000   1.000000   2.000000   0.000000   0.000000
25%        3.25000   0.000000   1.250000  22.000000   0.000000   0.000000
50%        5.50000   0.500000   3.000000  27.000000   0.500000   0.000000
75%        7.75000   1.000000   3.000000  35.000000   1.000000   0.000000
max       10.00000   1.000000   3.000000  54.000000   3.000000   2.000000

            Fare
count  10.000000
mean   27.020820
std    23.601938
min     7.250000
25%     8.152075
50%    16.104150
75%    46.414575
max    71.283300

In [67]:
titanic.describe(include=object)

                           Name   Sex     Ticket Cabin Embarked
count                        10    10         10     3       10
unique                       10     2         10     3        3
top     Braund, Mr. Owen Harris  male  A/5 21171   C85        S
freq                          1     5          1     1        7

In [68]:
titanic['Pclass'].unique()

array([3, 1, 2])

In [69]:
#запись DataFrame в файл
titanic.to_csv('updated_titanic.csv', sep=',', header=True, index=False)

## Часть 1: Структура данных Series

### Задание 1.1. Создание Series из списка Python

In [36]:
import pandas as pd
import numpy as np

# Создание Series из списка
s1 = pd.Series([10, 20, 30, 40, 50])
print("Series из списка:")
print(s1)
print(f"Тип: {type(s1)}")
print(f"Индексы: {s1.index}")
print(f"Значения: {s1.values}")

Series из списка:
0    10
1    20
2    30
3    40
4    50
dtype: int64
Тип: <class 'pandas.core.series.Series'>
Индексы: RangeIndex(start=0, stop=5, step=1)
Значения: [10 20 30 40 50]

### Задание 1.2. Создание Series из ndarray массива numpy

In [37]:
# Создание Series из массива numpy
arr = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
s2 = pd.Series(arr)
print("\nSeries из numpy массива:")
print(s2)

Series из numpy массива:
0    1.5
1    2.5
2    3.5
3    4.5
4    5.5
dtype: float64

### Задание 1.3. Создание Series из словаря (dict)

In [38]:
# Создание Series из словаря (ключи становятся индексами)
data_dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400}
s3 = pd.Series(data_dict)
print("\nSeries из словаря:")
print(s3)

Series из словаря:
a    100
b    200
c    300
d    400
dtype: int64

### Задание 1.4. Создание Series с использованием константы

In [39]:
# Создание Series с константным значением
s4 = pd.Series(5, index=range(1, 6))
print("\nSeries с константой 5 (индексы 1-5):")
print(s4)

# Создание Series с заданными индексами и константой
s5 = pd.Series(3.14, index=['x', 'y', 'z'])
print("\nSeries с константой 3.14 (индексы x,y,z):")
print(s5)

Series с константой 5 (индексы 1-5):
1    5
2    5
3    5
4    5
5    5
dtype: int64

Series с константой 3.14 (индексы x,y,z):
x    3.14
y    3.14
z    3.14
dtype: float64

### Задание 1.5. Работа с элементами Series — Обращение по индексу и метке

In [52]:
# Создаем Series для работы
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print("\nИсходный Series:")
print(s)

# ПРАВИЛЬНЫЙ способ: обращение по числовому индексу (позиции) через .iloc[]
print(f"\nЭлемент по позиции 0 (iloc[0]): {s.iloc[0]}")
print(f"Элемент по позиции 2 (iloc[2]): {s.iloc[2]}")

# Обращение по метке (label) через .loc[]
print(f"Элемент по метке 'a' (loc['a']): {s.loc['a']}")
print(f"Элемент по метке 'd' (loc['d']): {s.loc['d']}")

# Несколько элементов по позициям через .iloc[]
print(f"\nНесколько элементов по позициям [0, 2, 4]:\n{s.iloc[[0, 2, 4]]}")

# Несколько элементов по меткам через .loc[]
print(f"Несколько элементов по меткам ['a', 'c', 'e']:\n{s.loc[['a', 'c', 'e']]}")

Исходный Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Элемент по позиции 0 (iloc[0]): 10
Элемент по позиции 2 (iloc[2]): 30
Элемент по метке 'a' (loc['a']): 10
Элемент по метке 'd' (loc['d']): 40

Несколько элементов по позициям [0, 2, 4]:
a    10
c    30
e    50
dtype: int64
Несколько элементов по меткам ['a', 'c', 'e']:
a    10
c    30
e    50
dtype: int64

### Задание 1.6. Получение slice'ов (срезов)

In [41]:
# Срезы в Series
s = pd.Series([10, 20, 30, 40, 50, 60, 70], index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
print("\nИсходный Series:")
print(s)

# Срез по позициям (не включает правую границу)
print("\nСрез по позициям [2:5]:")
print(s[2:5])

# Срез по меткам (включает правую границу!)
print("\nСрез по меткам ['c':'e']:")
print(s['c':'e'])

# Срез с шагом
print("\nСрез с шагом 2 [::2]:")
print(s[::2])

# Обратный срез
print("\nОбратный срез [::-1]:")
print(s[::-1])

Исходный Series:
a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

Срез по позициям [2:5]:
c    30
d    40
e    50
dtype: int64

Срез по меткам ['c':'e']:
c    30
d    40
e    50
dtype: int64

Срез с шагом 2 [::2]:
a    10
c    30
e    50
g    70
dtype: int64

Обратный срез [::-1]:
g    70
f    60
e    50
d    40
c    30
b    20
a    10
dtype: int64

### Задание 1.7. Условные выражения (работа как с векторами)

In [42]:
# Условные выражения в Series
s = pd.Series([15, 25, 35, 45, 55], index=['a', 'b', 'c', 'd', 'e'])
print("\nИсходный Series:")
print(s)

# Сравнение (возвращает Series с boolean)
print("\ns > 30:")
print(s > 30)

# Фильтрация с использованием условия
print("\nЭлементы > 30:")
print(s[s > 30])

# Сложение с константой (векторизация)
print("\ns + 10:")
print(s + 10)

# Умножение на константу
print("\ns * 2:")
print(s * 2)

# Операции между Series
s2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print("\ns + s2:")
print(s + s2)

print("\ns * s2:")
print(s * s2)

# Сложные условия
print("\nЭлементы > 20 и < 50:")
print(s[(s > 20) & (s < 50)])

print("\nЭлементы <= 25 или >= 45:")
print(s[(s <= 25) | (s >= 45)])

Исходный Series:
a    15
b    25
c    35
d    45
e    55
dtype: int64

s > 30:
a    False
b    False
c     True
d     True
e     True
dtype: bool

Элементы > 30:
c    35
d    45
e    55
dtype: int64

s + 10:
a    25
b    35
c    45
d    55
e    65
dtype: int64

s * 2:
a     30
b     50
c     70
d     90
e    110
dtype: int64

s + s2:
a    16
b    27
c    38
d    49
e    60
dtype: int64

s * s2:
a     15
b     50
c    105
d    180
e    275
dtype: int64

Элементы > 20 и < 50:
b    25
c    35
d    45
dtype: int64

Элементы <= 25 или >= 45:
a    15
b    25
d    45
e    55
dtype: int64

## Часть 2: Структура данных DataFrame

### Задание 2.1. Создание DataFrame из словаря

In [43]:
# Создание DataFrame из словаря (ключи = названия столбцов)
data = {
    'Имя': ['Анна', 'Борис', 'Виктор', 'Галина'],
    'Возраст': [25, 30, 28, 24],
    'Город': ['Москва', 'СПб', 'Казань', 'Москва']
}
df1 = pd.DataFrame(data)
print("DataFrame из словаря:")
print(df1)
print(f"\nРазмер: {df1.shape}")
print(f"Столбцы: {df1.columns.tolist()}")

DataFrame из словаря:
      Имя  Возраст   Город
0    Анна       25  Москва
1   Борис       30     СПб
2  Виктор       28  Казань
3  Галина       24  Москва

Размер: (4, 3)
Столбцы: ['Имя', 'Возраст', 'Город']

### Задание 2.2. Создание DataFrame из списка словарей

In [44]:
# Создание DataFrame из списка словарей
data_list = [
    {'Имя': 'Анна', 'Возраст': 25, 'Город': 'Москва'},
    {'Имя': 'Борис', 'Возраст': 30, 'Город': 'СПб'},
    {'Имя': 'Виктор', 'Возраст': 28, 'Город': 'Казань'},
    {'Имя': 'Галина', 'Возраст': 24, 'Город': 'Москва'}
]
df2 = pd.DataFrame(data_list)
print("\nDataFrame из списка словарей:")
print(df2)

DataFrame из списка словарей:
      Имя  Возраст   Город
0    Анна       25  Москва
1   Борис       30     СПб
2  Виктор       28  Казань
3  Галина       24  Москва

### Задание 2.3. Создание DataFrame из двумерного массива

In [45]:
# Создание DataFrame из двумерного массива numpy
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
df3 = pd.DataFrame(arr_2d, columns=['A', 'B', 'C'], index=['row1', 'row2', 'row3', 'row4'])
print("\nDataFrame из двумерного массива:")
print(df3)

# Без указания индексов и столбцов
df4 = pd.DataFrame(arr_2d)
print("\nDataFrame без указания индексов/столбцов:")
print(df4)

DataFrame из двумерного массива:
       A   B   C
row1   1   2   3
row2   4   5   6
row3   7   8   9
row4  10  11  12

DataFrame без указания индексов/столбцов:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

## Часть 3: Работа с элементами DataFrame

### Задание 3.1. Выбор столбца

In [46]:
# Создаем DataFrame для работы
df = pd.DataFrame({
    'Имя': ['Анна', 'Борис', 'Виктор', 'Галина', 'Дмитрий'],
    'Возраст': [25, 30, 28, 24, 27],
    'Зарплата': [50000, 60000, 55000, 48000, 52000],
    'Город': ['Москва', 'СПб', 'Казань', 'Москва', 'СПб']
})
print("Исходный DataFrame:")
print(df)

# Выбор одного столбца (возвращает Series)
print("\nВыбор столбца 'Имя':")
print(df['Имя'])
print(f"Тип: {type(df['Имя'])}")

# Альтернативный способ (через точку)
print("\nВыбор столбца 'Возраст' через точку:")
print(df.Возраст)

# Выбор нескольких столбцов (возвращает DataFrame)
print("\nВыбор нескольких столбцов ['Имя', 'Зарплата']:")
print(df[['Имя', 'Зарплата']])

Исходный DataFrame:
       Имя  Возраст  Зарплата   Город
0     Анна       25     50000  Москва
1    Борис       30     60000     СПб
2   Виктор       28     55000  Казань
3   Галина       24     48000  Москва
4  Дмитрий       27     52000     СПб

Выбор столбца 'Имя':
0       Анна
1      Борис
2     Виктор
3     Галина
4    Дмитрий
Name: Имя, dtype: object
Тип: <class 'pandas.core.series.Series'>

Выбор столбца 'Возраст' через точку:
0    25
1    30
2    28
3    24
4    27
Name: Возраст, dtype: int64

Выбор нескольких столбцов ['Имя', 'Зарплата']:
       Имя  Зарплата
0     Анна     50000
1    Борис     60000
2   Виктор     55000
3   Галина     48000
4  Дмитрий     52000

### Задание 3.2. Выбор строки по метке (loc)

In [47]:
# Устанавливаем индексы
df_with_index = df.set_index('Имя')
print("DataFrame с индексами по именам:")
print(df_with_index)

# Выбор строки по метке
print("\nСтрока с меткой 'Виктор':")
print(df_with_index.loc['Виктор'])

# Выбор нескольких строк по меткам
print("\nСтроки с метками ['Анна', 'Галина']:")
print(df_with_index.loc[['Анна', 'Галина']])

# Выбор строк и столбцов одновременно
print("\nСтрока 'Борис', столбцы 'Возраст' и 'Зарплата':")
print(df_with_index.loc['Борис', ['Возраст', 'Зарплата']])

DataFrame с индексами по именам:
         Возраст  Зарплата   Город
Имя
Анна          25     50000  Москва
Борис         30     60000     СПб
Виктор        28     55000  Казань
Галина        24     48000  Москва
Дмитрий       27     52000     СПб

Строка с меткой 'Виктор':
Возраст         28
Зарплата     55000
Город       Казань
Name: Виктор, dtype: object

Строки с метками ['Анна', 'Галина']:
        Возраст  Зарплата   Город
Имя
Анна         25     50000  Москва
Галина       24     48000  Москва

Строка 'Борис', столбцы 'Возраст' и 'Зарплата':
Возраст        30
Зарплата    60000
Name: Борис, dtype: object

### Задание 3.3. Выбор строки по индексу (iloc)

In [48]:
# Выбор строки по числовому индексу (позиции)
print("\nСтрока с индексом 2 (третья строка):")
print(df.iloc[2])

# Выбор нескольких строк по позициям
print("\nСтроки с индексами 0 и 3:")
print(df.iloc[[0, 3]])

# Срез по строкам (с 1 по 3, не включая 4)
print("\nСтроки с 1 по 3 (индексы 1,2,3):")
print(df.iloc[1:4])

# Выбор строк и столбцов по позициям
print("\nСтроки 0-2, столбцы 1-3:")
print(df.iloc[0:3, 1:4])

Строка с индексом 2 (третья строка):
Имя         Виктор
Возраст         28
Зарплата     55000
Город       Казань
Name: 2, dtype: object

Строки с индексами 0 и 3:
      Имя  Возраст  Зарплата   Город
0    Анна       25     50000  Москва
3  Галина       24     48000  Москва

Строки с 1 по 3 (индексы 1,2,3):
      Имя  Возраст  Зарплата   Город
1   Борис       30     60000     СПб
2  Виктор       28     55000  Казань
3  Галина       24     48000  Москва

Строки 0-2, столбцы 1-3:
   Возраст  Зарплата   Город
0       25     50000  Москва
1       30     60000     СПб
2       28     55000  Казань

### Задание 3.4. Слайс по строкам

In [49]:
# Различные способы слайсинга строк
print("Исходный DataFrame:")
print(df)

# Слайс с использованием числовых индексов
print("\nСлайс df[1:4]:")
print(df[1:4])

# Слайс с шагом
print("\nСлайс df[::2] (каждая вторая строка):")
print(df[::2])

# Слайс с использованием loc (по меткам индекса)
df_indexed = df.set_index('Имя')
print("\nDataFrame с индексом по именам:")
print(df_indexed)
print("\nСлайс по меткам ['Борис':'Галина']:")
print(df_indexed.loc['Борис':'Галина'])

Исходный DataFrame:
       Имя  Возраст  Зарплата   Город
0     Анна       25     50000  Москва
1    Борис       30     60000     СПб
2   Виктор       28     55000  Казань
3   Галина       24     48000  Москва
4  Дмитрий       27     52000     СПб

Слайс df[1:4]:
      Имя  Возраст  Зарплата   Город
1   Борис       30     60000     СПб
2  Виктор       28     55000  Казань
3  Галина       24     48000  Москва

Слайс df[::2] (каждая вторая строка):
       Имя  Возраст  Зарплата   Город
0     Анна       25     50000  Москва
2   Виктор       28     55000  Казань
4  Дмитрий       27     52000     СПб

DataFrame с индексом по именам:
         Возраст  Зарплата   Город
Имя
Анна          25     50000  Москва
Борис         30     60000     СПб
Виктор        28     55000  Казань
Галина        24     48000  Москва
Дмитрий       27     52000     СПб

Слайс по меткам ['Борис':'Галина']:
        Возраст  Зарплата   Город
Имя
Борис        30     60000     СПб
Виктор       28     55000  Казань
Галина       24     48000  Москва

### Задание 3.5. Выбор строки по условию

In [50]:
# Фильтрация строк по условию
print("Исходный DataFrame:")
print(df)

# Условие: возраст > 26
print("\nСотрудники с возрастом > 26:")
print(df[df['Возраст'] > 26])

# Условие: зарплата >= 55000
print("\nСотрудники с зарплатой >= 55000:")
print(df[df['Зарплата'] >= 55000])

# Составное условие (И)
print("\nСотрудники из Москвы с зарплатой > 50000:")
print(df[(df['Город'] == 'Москва') & (df['Зарплата'] > 50000)])

# Составное условие (ИЛИ)
print("\nСотрудники из Москвы ИЛИ с зарплатой > 55000:")
print(df[(df['Город'] == 'Москва') | (df['Зарплата'] > 55000)])

# Использование .query()
print("\nИспользование query(): возраст между 25 и 28:")
print(df.query('25 <= Возраст <= 28'))

# Условие с isin()
cities = ['Москва', 'Казань']
print(f"\nСотрудники из городов {cities}:")
print(df[df['Город'].isin(cities)])

Исходный DataFrame:
       Имя  Возраст  Зарплата   Город
0     Анна       25     50000  Москва
1    Борис       30     60000     СПб
2   Виктор       28     55000  Казань
3   Галина       24     48000  Москва
4  Дмитрий       27     52000     СПб

Сотрудники с возрастом > 26:
       Имя  Возраст  Зарплата   Город
1    Борис       30     60000     СПб
2   Виктор       28     55000  Казань
4  Дмитрий       27     52000     СПб

Сотрудники с зарплатой >= 55000:
      Имя  Возраст  Зарплата   Город
1   Борис       30     60000     СПб
2  Виктор       28     55000  Казань

Сотрудники из Москвы с зарплатой > 50000:
Empty DataFrame
Columns: [Имя, Возраст, Зарплата, Город]
Index: []

Сотрудники из Москвы ИЛИ с зарплатой > 55000:
      Имя  Возраст  Зарплата   Город
0    Анна       25     50000  Москва
1   Борис       30     60000     СПб
3  Галина       24     48000  Москва

Использование query(): возраст между 25 и 28:
       Имя  Возраст  Зарплата   Город
0     Анна       25     50000  Москва
2   Виктор       28     55000  Казань
4  Дмитрий       27     52000     СПб

Сотрудники из городов ['Москва', 'Казань']:
      Имя  Возраст  Зарплата   Город
0    Анна       25     50000  Москва
2  Виктор       28     55000  Казань
3  Галина       24     48000  Москва

### Задание 3.6. Запись датафрейма в файл

In [51]:
# Запись DataFrame в различные форматы

# 1. Запись в CSV
df.to_csv('employees.csv', index=False, encoding='utf-8-sig')
print("\nDataFrame записан в 'employees.csv'")

# 2. Запись в CSV с индексами
df.to_csv('employees_with_index.csv', encoding='utf-8-sig')
print("DataFrame записан в 'employees_with_index.csv' (с индексами)")

# 3. Запись в Excel (требуется openpyxl или xlsxwriter)
try:
    df.to_excel('employees.xlsx', index=False, sheet_name='Сотрудники')
    print("DataFrame записан в 'employees.xlsx'")
except Exception as e:
    print(f"Excel не поддерживается: {e}")

# 4. Запись в JSON
df.to_json('employees.json', orient='records', force_ascii=False, indent=2)
print("DataFrame записан в 'employees.json'")

# 5. Запись в HTML
df.to_html('employees.html', index=False)
print("DataFrame записан в 'employees.html'")

# 6. Запись в Markdown
try:
    print("\nDataFrame в Markdown формате:")
    print(df.to_markdown())
except:
    print("Markdown требует установки tabulate: pip install tabulate")

# 7. Запись в Clipboard (для вставки в Excel/Google Sheets)
df.to_clipboard(index=False, excel=True)
print("\nDataFrame скопирован в буфер обмена (можно вставить в Excel)")

# Проверка созданных файлов
import os
print("\nСозданные файлы:")
for file in ['employees.csv', 'employees_with_index.csv', 'employees.json', 'employees.html']:
    if os.path.exists(file):
        size = os.path.getsize(file)
        print(f"  {file} ({size} байт)")

DataFrame записан в 'employees.csv'
DataFrame записан в 'employees_with_index.csv' (с индексами)
DataFrame записан в 'employees.xlsx'
DataFrame записан в 'employees.json'
DataFrame записан в 'employees.html'

DataFrame в Markdown формате:
|    | Имя     |   Возраст |   Зарплата | Город   |
|---:|:--------|----------:|-----------:|:--------|
|  0 | Анна    |        25 |      50000 | Москва  |
|  1 | Борис   |        30 |      60000 | СПб     |
|  2 | Виктор  |        28 |      55000 | Казань  |
|  3 | Галина  |        24 |      48000 | Москва  |
|  4 | Дмитрий |        27 |      52000 | СПб     |

DataFrame скопирован в буфер обмена (можно вставить в Excel)

Созданные файлы:
  employees.csv (218 байт)
  employees_with_index.csv (229 байт)
  employees.json (611 байт)
  employees.html (797 байт)

## Практика